from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).parents[1]
MANIFEST = ROOT / "configs" / "tool-manifest.json"
OUTPUT = ROOT / "standards" / "SUPPORT_MATRIX.md"


def main() -> None:
    tools = json.loads(MANIFEST.read_text(encoding="utf-8"))["tools"]
    lines = [
        "<!-- Generated by scripts/gen_support_matrix.py; do not edit manually. -->",
        "# Generated support matrix",
        "",
        "Support labels name the verified capability, not a blanket claim that every",
        "language has complete behavioral verification. An unsupported or unavailable",
        "tool is emitted explicitly and cannot satisfy a required gate.",
        "",
        "| Tool | Capabilities | Languages/file kinds | Platforms | Auto-install | Certification |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    for tool in sorted(tools, key=lambda item: item["id"].lower()):
        scopes = [*tool.get("languages", []), *tool.get("file_kinds", [])]
        install = tool.get("auto_install", {})
        support = "yes" if install.get("supported") else "no"
        if not install.get("supported") and install.get("reason"):
            support += f" — {install['reason']}"
        cells = (
            tool["id"],
            ", ".join(tool.get("capabilities", [])) or "—",
            ", ".join(scopes) or "all/project",
            ", ".join(tool.get("platforms", [])) or "—",
            support,
            "declared adapter; verify with conformance fixture",
        )
        lines.append(
            "| " + " | ".join(cell.replace("|", "\\|") for cell in cells) + " |"
        )
    OUTPUT.write_text("\n".join(lines) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
